
FROM postgres:16-bullseye

# Instal postgresql-contrib (untuk GIN, pg_trgm) dan pg_cron
# Perintah ini memerlukan akses root (sudo di luar container)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    postgresql-contrib \
    postgresql-16-cron \
    # 2. Instal pgvector dari repositori PGDG (ini adalah cara paling stabil)
    postgresql-16-pgvector && \
    rm -rf /var/lib/apt/lists/*