/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  app: {
    AiAgents: () => import('#controllers/app/ai_agents_controller'),
    AiAssets: () => import('#controllers/app/ai_assets_controller'),
    AiKnowledge: () => import('#controllers/app/ai_knowledge_controller'),
    AiPlaybooks: () => import('#controllers/app/ai_playbooks_controller'),
    Analytics: () => import('#controllers/app/analytics_controller'),
    AuditLogs: () => import('#controllers/app/audit_logs_controller'),
    Billing: () => import('#controllers/app/billing_controller'),
    Channels: () => import('#controllers/app/channels_controller'),
    Chats: () => import('#controllers/app/chats_controller'),
    Contacts: () => import('#controllers/app/contacts_controller'),
    Conversations: () => import('#controllers/app/conversations_controller'),
    Divisions: () => import('#controllers/app/divisions_controller'),
    Labels: () => import('#controllers/app/labels_controller'),
    Messages: () => import('#controllers/app/messages_controller'),
    QuickReplies: () => import('#controllers/app/quick_replies_controller'),
    Realtime: () => import('#controllers/app/realtime_controller'),
    Search: () => import('#controllers/app/search_controller'),
    Team: () => import('#controllers/app/team_controller'),
    Uploads: () => import('#controllers/app/uploads_controller'),
  },
  Auth: () => import('#controllers/auth_controller'),
  BillingWebhooks: () => import('#controllers/billing_webhooks_controller'),
  Health: () => import('#controllers/health_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Oauth: () => import('#controllers/oauth_controller'),
  Robots: () => import('#controllers/robots_controller'),
  Session: () => import('#controllers/session_controller'),
  Sitemaps: () => import('#controllers/sitemaps_controller'),
  SuperAdmin: () => import('#controllers/super_admin_controller'),
  Webchat: () => import('#controllers/webchat_controller'),
  Webhooks: () => import('#controllers/webhooks_controller'),
}
