package seeders

import (
	"context"
	"social-forge/internal/entity"
	"social-forge/internal/infra/contextpool"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"
)

func (s *Seeder) RoleSeed(ctx context.Context) error {
	subCtx, cancel := contextpool.WithTimeoutIfNone(ctx, 5*time.Second)
	defer cancel()

	roles := []entity.Role{
		{
			ID:          uuid.New(),
			Name:        entity.RoleSuperAdmin,
			Slug:        entity.RoleSuperAdmin,
			Description: entity.NewNullString("Super admin role"),
			Level:       entity.RoleLevelSuperAdmin,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        entity.RoleAdmin,
			Slug:        entity.RoleAdmin,
			Description: entity.NewNullString("Admin role"),
			Level:       entity.RoleLevelAdmin,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        entity.RoleTenantOwner,
			Slug:        entity.RoleTenantOwner,
			Description: entity.NewNullString("Tenant owner role"),
			Level:       entity.RoleLevelTenantOwner,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        entity.RoleSupervisor,
			Slug:        entity.RoleSupervisor,
			Description: entity.NewNullString("Supervisor role"),
			Level:       entity.RoleLevelSupervisor,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        entity.RoleAgent,
			Slug:        entity.RoleAgent,
			Description: entity.NewNullString("Agent role"),
			Level:       entity.RoleLevelAgent,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
	}

	var anyError error
	for _, role := range roles {
		if err := s.roleRepo.Create(subCtx, &role); err != nil {
			s.logger.Error("Failed to create role", zap.Error(err))
			if anyError == nil {
				anyError = err
			}
			continue
		}
	}
	if anyError != nil {
		s.logger.Error("Failed to seed roles", zap.Error(anyError))
		return anyError
	}
	s.logger.Info("Successfully seeded roles")
	return nil
}
func (s *Seeder) PermissionSeed(ctx context.Context) error {
	subCtx, cancel := contextpool.WithTimeoutFallback(ctx, 2*time.Minute)
	defer cancel()

	permissions := []entity.Permission{
		{
			ID:          uuid.New(),
			Name:        "manage_roles",
			Slug:        "manage_roles",
			Resource:    entity.ResourceUsers,
			Action:      entity.ActionManage,
			Description: entity.NewNullString("Manage roles"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "manage_tenants",
			Slug:        "manage_tenants",
			Resource:    entity.ResourceTenants,
			Action:      entity.ActionManage,
			Description: entity.NewNullString("Manage tenants"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "manage_divisions",
			Slug:        "manage_divisions",
			Resource:    entity.ResourceDivisions,
			Action:      entity.ActionManage,
			Description: entity.NewNullString("Manage divisions"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "manage_agents",
			Slug:        "manage_agents",
			Resource:    entity.ResourceAgents,
			Action:      entity.ActionManage,
			Description: entity.NewNullString("Manage agents"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "manage_conversations",
			Slug:        "manage_conversations",
			Resource:    entity.ResourceConversations,
			Action:      entity.ActionManage,
			Description: entity.NewNullString("Manage conversations"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "manage_messages",
			Slug:        "manage_messages",
			Resource:    entity.ResourceMessages,
			Action:      entity.ActionManage,
			Description: entity.NewNullString("Manage messages"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "manage_contacts",
			Slug:        "manage_contacts",
			Resource:    entity.ResourceContacts,
			Action:      entity.ActionManage,
			Description: entity.NewNullString("Manage contacts"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "manage_quick_replies",
			Slug:        "manage_quick_replies",
			Resource:    entity.ResourceQuickReplies,
			Action:      entity.ActionManage,
			Description: entity.NewNullString("Manage quick replies"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "manage_auto_replies",
			Slug:        "manage_auto_replies",
			Resource:    entity.ResourceAutoReplies,
			Action:      entity.ActionManage,
			Description: entity.NewNullString("Manage auto replies"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "manage_pages",
			Slug:        "manage_pages",
			Resource:    entity.ResourcePages,
			Action:      entity.ActionManage,
			Description: entity.NewNullString("Manage pages"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "manage_channels",
			Slug:        "manage_channels",
			Resource:    entity.ResourceChannels,
			Action:      entity.ActionManage,
			Description: entity.NewNullString("Manage channels"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "manage_analytics",
			Slug:        "manage_analytics",
			Resource:    entity.ResourceAnalytics,
			Action:      entity.ActionManage,
			Description: entity.NewNullString("Manage analytics"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "manage_settings",
			Slug:        "manage_settings",
			Resource:    entity.ResourceSettings,
			Action:      entity.ActionManage,
			Description: entity.NewNullString("Manage settings"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "read_roles",
			Slug:        "read_roles",
			Resource:    entity.ResourceUsers,
			Action:      entity.ActionRead,
			Description: entity.NewNullString("Read roles"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "read_tenants",
			Slug:        "read_tenants",
			Resource:    entity.ResourceTenants,
			Action:      entity.ActionRead,
			Description: entity.NewNullString("Read tenants"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "read_divisions",
			Slug:        "read_divisions",
			Resource:    entity.ResourceDivisions,
			Action:      entity.ActionRead,
			Description: entity.NewNullString("Read divisions"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "read_agents",
			Slug:        "read_agents",
			Resource:    entity.ResourceAgents,
			Action:      entity.ActionRead,
			Description: entity.NewNullString("Read agents"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "read_conversations",
			Slug:        "read_conversations",
			Resource:    entity.ResourceConversations,
			Action:      entity.ActionRead,
			Description: entity.NewNullString("Read conversations"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "read_messages",
			Slug:        "read_messages",
			Resource:    entity.ResourceMessages,
			Action:      entity.ActionRead,
			Description: entity.NewNullString("Read messages"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "read_contacts",
			Slug:        "read_contacts",
			Resource:    entity.ResourceContacts,
			Action:      entity.ActionRead,
			Description: entity.NewNullString("Read contacts"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "read_quick_replies",
			Slug:        "read_quick_replies",
			Resource:    entity.ResourceQuickReplies,
			Action:      entity.ActionRead,
			Description: entity.NewNullString("Read quick replies"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "read_auto_replies",
			Slug:        "read_auto_replies",
			Resource:    entity.ResourceAutoReplies,
			Action:      entity.ActionRead,
			Description: entity.NewNullString("Read auto replies"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "read_pages",
			Slug:        "read_pages",
			Resource:    entity.ResourcePages,
			Action:      entity.ActionRead,
			Description: entity.NewNullString("Read pages"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "read_channels",
			Slug:        "read_channels",
			Resource:    entity.ResourceChannels,
			Action:      entity.ActionRead,
			Description: entity.NewNullString("Read channels"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "read_analytics",
			Slug:        "read_analytics",
			Resource:    entity.ResourceAnalytics,
			Action:      entity.ActionRead,
			Description: entity.NewNullString("Read analytics"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "read_settings",
			Slug:        "read_settings",
			Resource:    entity.ResourceSettings,
			Action:      entity.ActionRead,
			Description: entity.NewNullString("Read settings"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "create_roles",
			Slug:        "create_roles",
			Resource:    entity.ResourceUsers,
			Action:      entity.ActionCreate,
			Description: entity.NewNullString("Create roles"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "create_tenants",
			Slug:        "create_tenants",
			Resource:    entity.ResourceTenants,
			Action:      entity.ActionCreate,
			Description: entity.NewNullString("Create tenants"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "create_divisions",
			Slug:        "create_divisions",
			Resource:    entity.ResourceDivisions,
			Action:      entity.ActionCreate,
			Description: entity.NewNullString("Create divisions"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "create_agents",
			Slug:        "create_agents",
			Resource:    entity.ResourceAgents,
			Action:      entity.ActionCreate,
			Description: entity.NewNullString("Create agents"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "create_conversations",
			Slug:        "create_conversations",
			Resource:    entity.ResourceConversations,
			Action:      entity.ActionCreate,
			Description: entity.NewNullString("Create conversations"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "create_messages",
			Slug:        "create_messages",
			Resource:    entity.ResourceMessages,
			Action:      entity.ActionCreate,
			Description: entity.NewNullString("Create messages"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "create_contacts",
			Slug:        "create_contacts",
			Resource:    entity.ResourceContacts,
			Action:      entity.ActionCreate,
			Description: entity.NewNullString("Create contacts"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "create_quick_replies",
			Slug:        "create_quick_replies",
			Resource:    entity.ResourceQuickReplies,
			Action:      entity.ActionCreate,
			Description: entity.NewNullString("Create quick replies"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "create_auto_replies",
			Slug:        "create_auto_replies",
			Resource:    entity.ResourceAutoReplies,
			Action:      entity.ActionCreate,
			Description: entity.NewNullString("Create auto replies"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "create_pages",
			Slug:        "create_pages",
			Resource:    entity.ResourcePages,
			Action:      entity.ActionCreate,
			Description: entity.NewNullString("Create pages"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "create_channels",
			Slug:        "create_channels",
			Resource:    entity.ResourceChannels,
			Action:      entity.ActionCreate,
			Description: entity.NewNullString("Create channels"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "create_analytics",
			Slug:        "create_analytics",
			Resource:    entity.ResourceAnalytics,
			Action:      entity.ActionCreate,
			Description: entity.NewNullString("Create analytics"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "create_settings",
			Slug:        "create_settings",
			Resource:    entity.ResourceSettings,
			Action:      entity.ActionCreate,
			Description: entity.NewNullString("Create settings"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "update_roles",
			Slug:        "update_roles",
			Resource:    entity.ResourceUsers,
			Action:      entity.ActionUpdate,
			Description: entity.NewNullString("Update roles"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "update_tenants",
			Slug:        "update_tenants",
			Resource:    entity.ResourceTenants,
			Action:      entity.ActionUpdate,
			Description: entity.NewNullString("Update tenants"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "update_divisions",
			Slug:        "update_divisions",
			Resource:    entity.ResourceDivisions,
			Action:      entity.ActionUpdate,
			Description: entity.NewNullString("Update divisions"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "update_agents",
			Slug:        "update_agents",
			Resource:    entity.ResourceAgents,
			Action:      entity.ActionUpdate,
			Description: entity.NewNullString("Update agents"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "update_conversations",
			Slug:        "update_conversations",
			Resource:    entity.ResourceConversations,
			Action:      entity.ActionUpdate,
			Description: entity.NewNullString("Update conversations"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "update_messages",
			Slug:        "update_messages",
			Resource:    entity.ResourceMessages,
			Action:      entity.ActionUpdate,
			Description: entity.NewNullString("Update messages"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "update_contacts",
			Slug:        "update_contacts",
			Resource:    entity.ResourceContacts,
			Action:      entity.ActionUpdate,
			Description: entity.NewNullString("Update contacts"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "update_quick_replies",
			Slug:        "update_quick_replies",
			Resource:    entity.ResourceQuickReplies,
			Action:      entity.ActionUpdate,
			Description: entity.NewNullString("Update quick replies"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "update_auto_replies",
			Slug:        "update_auto_replies",
			Resource:    entity.ResourceAutoReplies,
			Action:      entity.ActionUpdate,
			Description: entity.NewNullString("Update auto replies"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "update_pages",
			Slug:        "update_pages",
			Resource:    entity.ResourcePages,
			Action:      entity.ActionUpdate,
			Description: entity.NewNullString("Update pages"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "update_channels",
			Slug:        "update_channels",
			Resource:    entity.ResourceChannels,
			Action:      entity.ActionUpdate,
			Description: entity.NewNullString("Update channels"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "update_analytics",
			Slug:        "update_analytics",
			Resource:    entity.ResourceAnalytics,
			Action:      entity.ActionUpdate,
			Description: entity.NewNullString("Update analytics"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "update_settings",
			Slug:        "update_settings",
			Resource:    entity.ResourceSettings,
			Action:      entity.ActionUpdate,
			Description: entity.NewNullString("Update settings"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "delete_roles",
			Slug:        "delete_roles",
			Resource:    entity.ResourceUsers,
			Action:      entity.ActionDelete,
			Description: entity.NewNullString("Delete roles"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "delete_tenants",
			Slug:        "delete_tenants",
			Resource:    entity.ResourceTenants,
			Action:      entity.ActionDelete,
			Description: entity.NewNullString("Delete tenants"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "delete_divisions",
			Slug:        "delete_divisions",
			Resource:    entity.ResourceDivisions,
			Action:      entity.ActionDelete,
			Description: entity.NewNullString("Delete divisions"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "delete_agents",
			Slug:        "delete_agents",
			Resource:    entity.ResourceAgents,
			Action:      entity.ActionDelete,
			Description: entity.NewNullString("Delete agents"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "delete_conversations",
			Slug:        "delete_conversations",
			Resource:    entity.ResourceConversations,
			Action:      entity.ActionDelete,
			Description: entity.NewNullString("Delete conversations"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "delete_messages",
			Slug:        "delete_messages",
			Resource:    entity.ResourceMessages,
			Action:      entity.ActionDelete,
			Description: entity.NewNullString("Delete messages"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "delete_contacts",
			Slug:        "delete_contacts",
			Resource:    entity.ResourceContacts,
			Action:      entity.ActionDelete,
			Description: entity.NewNullString("Delete contacts"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "delete_quick_replies",
			Slug:        "delete_quick_replies",
			Resource:    entity.ResourceQuickReplies,
			Action:      entity.ActionDelete,
			Description: entity.NewNullString("Delete quick replies"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "delete_auto_replies",
			Slug:        "delete_auto_replies",
			Resource:    entity.ResourceAutoReplies,
			Action:      entity.ActionDelete,
			Description: entity.NewNullString("Delete auto replies"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "delete_pages",
			Slug:        "delete_pages",
			Resource:    entity.ResourcePages,
			Action:      entity.ActionDelete,
			Description: entity.NewNullString("Delete pages"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "delete_channels",
			Slug:        "delete_channels",
			Resource:    entity.ResourceChannels,
			Action:      entity.ActionDelete,
			Description: entity.NewNullString("Delete channels"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "delete_analytics",
			Slug:        "delete_analytics",
			Resource:    entity.ResourceAnalytics,
			Action:      entity.ActionDelete,
			Description: entity.NewNullString("Delete analytics"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "delete_settings",
			Slug:        "delete_settings",
			Resource:    entity.ResourceSettings,
			Action:      entity.ActionDelete,
			Description: entity.NewNullString("Delete settings"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "assign_roles",
			Slug:        "assign_roles",
			Resource:    entity.ResourceUsers,
			Action:      entity.ActionAssign,
			Description: entity.NewNullString("Assign roles"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "assign_tenants",
			Slug:        "assign_tenants",
			Resource:    entity.ResourceTenants,
			Action:      entity.ActionAssign,
			Description: entity.NewNullString("Assign tenants"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "assign_divisions",
			Slug:        "assign_divisions",
			Resource:    entity.ResourceDivisions,
			Action:      entity.ActionAssign,
			Description: entity.NewNullString("Assign divisions"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "assign_agents",
			Slug:        "assign_agents",
			Resource:    entity.ResourceAgents,
			Action:      entity.ActionAssign,
			Description: entity.NewNullString("Assign agents"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "assign_conversations",
			Slug:        "assign_conversations",
			Resource:    entity.ResourceConversations,
			Action:      entity.ActionAssign,
			Description: entity.NewNullString("Assign conversations"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "assign_messages",
			Slug:        "assign_messages",
			Resource:    entity.ResourceMessages,
			Action:      entity.ActionAssign,
			Description: entity.NewNullString("Assign messages"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "assign_contacts",
			Slug:        "assign_contacts",
			Resource:    entity.ResourceContacts,
			Action:      entity.ActionAssign,
			Description: entity.NewNullString("Assign contacts"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "assign_quick_replies",
			Slug:        "assign_quick_replies",
			Resource:    entity.ResourceQuickReplies,
			Action:      entity.ActionAssign,
			Description: entity.NewNullString("Assign quick replies"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "assign_auto_replies",
			Slug:        "assign_auto_replies",
			Resource:    entity.ResourceAutoReplies,
			Action:      entity.ActionAssign,
			Description: entity.NewNullString("Assign auto replies"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "assign_pages",
			Slug:        "assign_pages",
			Resource:    entity.ResourcePages,
			Action:      entity.ActionAssign,
			Description: entity.NewNullString("Assign pages"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "assign_channels",
			Slug:        "assign_channels",
			Resource:    entity.ResourceChannels,
			Action:      entity.ActionAssign,
			Description: entity.NewNullString("Assign channels"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "assign_analytics",
			Slug:        "assign_analytics",
			Resource:    entity.ResourceAnalytics,
			Action:      entity.ActionAssign,
			Description: entity.NewNullString("Assign analytics"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "assign_settings",
			Slug:        "assign_settings",
			Resource:    entity.ResourceSettings,
			Action:      entity.ActionAssign,
			Description: entity.NewNullString("Assign settings"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "export_roles",
			Slug:        "export_roles",
			Resource:    entity.ResourceUsers,
			Action:      entity.ActionExport,
			Description: entity.NewNullString("Export roles"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "export_tenants",
			Slug:        "export_tenants",
			Resource:    entity.ResourceTenants,
			Action:      entity.ActionExport,
			Description: entity.NewNullString("Export tenants"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "export_divisions",
			Slug:        "export_divisions",
			Resource:    entity.ResourceDivisions,
			Action:      entity.ActionExport,
			Description: entity.NewNullString("Export divisions"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "export_agents",
			Slug:        "export_agents",
			Resource:    entity.ResourceAgents,
			Action:      entity.ActionExport,
			Description: entity.NewNullString("Export agents"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "export_conversations",
			Slug:        "export_conversations",
			Resource:    entity.ResourceConversations,
			Action:      entity.ActionExport,
			Description: entity.NewNullString("Export conversations"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "export_messages",
			Slug:        "export_messages",
			Resource:    entity.ResourceMessages,
			Action:      entity.ActionExport,
			Description: entity.NewNullString("Export messages"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "export_contacts",
			Slug:        "export_contacts",
			Resource:    entity.ResourceContacts,
			Action:      entity.ActionExport,
			Description: entity.NewNullString("Export contacts"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "export_quick_replies",
			Slug:        "export_quick_replies",
			Resource:    entity.ResourceQuickReplies,
			Action:      entity.ActionExport,
			Description: entity.NewNullString("Export quick replies"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "export_auto_replies",
			Slug:        "export_auto_replies",
			Resource:    entity.ResourceAutoReplies,
			Action:      entity.ActionExport,
			Description: entity.NewNullString("Export auto replies"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "export_pages",
			Slug:        "export_pages",
			Resource:    entity.ResourcePages,
			Action:      entity.ActionExport,
			Description: entity.NewNullString("Export pages"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "export_channels",
			Slug:        "export_channels",
			Resource:    entity.ResourceChannels,
			Action:      entity.ActionExport,
			Description: entity.NewNullString("Export channels"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "export_analytics",
			Slug:        "export_analytics",
			Resource:    entity.ResourceAnalytics,
			Action:      entity.ActionExport,
			Description: entity.NewNullString("Export analytics"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			ID:          uuid.New(),
			Name:        "export_settings",
			Slug:        "export_settings",
			Resource:    entity.ResourceSettings,
			Action:      entity.ActionExport,
			Description: entity.NewNullString("Export settings"),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
	}

	var anyError error
	for _, permission := range permissions {
		if err := s.permissionRepo.Create(subCtx, &permission); err != nil {
			s.logger.Error("Failed to create permission", zap.Error(err))
			if anyError == nil {
				anyError = err
			}
			continue
		}
	}
	if anyError != nil {
		s.logger.Error("Failed to seed permissions", zap.Error(anyError))
		return anyError
	}
	s.logger.Info("Successfully seeded permissions")
	return nil
}
func (s *Seeder) RolePermissionSeed(ctx context.Context) error {
	subCtx, cancel := contextpool.WithTimeoutFallback(ctx, 10*time.Minute)
	defer cancel()

	roles, err := s.roleRepo.GetAll(subCtx)
	if err != nil {
		s.logger.Error("Failed to get roles", zap.Error(err))
		return err
	}
	permissions, err := s.permissionRepo.GetAll(subCtx)
	if err != nil {
		s.logger.Error("Failed to get permissions", zap.Error(err))
		return err
	}

	rolePermissions := []entity.RolePermission{}
	for _, role := range roles {
		for _, permission := range permissions {
			rolePermissions = append(rolePermissions, entity.RolePermission{
				RoleID:       role.ID,
				PermissionID: permission.ID,
			})
		}
	}
	if err := s.rolePermissionRepo.CreateBatch(subCtx, rolePermissions); err != nil {
		s.logger.Error("Failed to create role permissions", zap.Error(err))
		return err
	}
	s.logger.Info("Successfully seeded role permissions")
	return nil
}
