# mongod.conf
storage:
  dbPath: /data/db
  journal:
    enabled: true
  wiredTiger:
    engineConfig:
      cacheSizeGB: 1

net:
  port: 27017
  bindIp: 0.0.0.0  # Allows connections from outside the container

security:
  authorization: enabled  # Enables username/password authentication

operationProfiling:
  mode: slowOp
  slowOpThresholdMs: 100
