global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'socialforge'
    environment: 'production'

# Alerting configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# Rule files (optional)
# rule_files:
#   - 'alerts.yml'

scrape_configs:
# Prometheus self-monitoring
- job_name: 'prometheus'
  static_configs:
  - targets: [ 'localhost:9090' ]

# Backend API metrics
- job_name: 'backend'
  static_configs:
  - targets: [ 'backend:8080' ]
  metrics_path: '/metrics'
  scrape_interval: 10s
  scrape_timeout: 5s

# Centrifugo metrics
- job_name: 'centrifugo'
  static_configs:
  - targets: [ 'centrifugo:8000' ]
  metrics_path: '/metrics'

# PostgreSQL metrics (using postgres_exporter)
# - job_name: 'postgres'
#   static_configs:
#     - targets: ['postgres-exporter:9187']

# Redis metrics (using redis_exporter)
# - job_name: 'redis'
#   static_configs:
#     - targets: ['redis-exporter:9121']

# Node exporter for system metrics
# - job_name: 'node'
#   static_configs:
#     - targets: ['node-exporter:9100']

# MinIO metrics
- job_name: 'minio'
  metrics_path: /minio/v2/metrics/cluster
  static_configs:
  - targets: [ 'minio:9000' ]

# Docker container metrics (using cadvisor)
# - job_name: 'cadvisor'
#   static_configs:
#     - targets: ['cadvisor:8080']
